version: "3"
services:
  user:
#   网络模式设置host的话，那么 容器将使用宿主机IP地址，否则默认使用bridge会新生成一个IP
#   设置为host的话，应用jar包启动如果设置了localhost访问数据库那是可以的，但是如果不设置
#   因为容器用自己的IP，那么localhost是访问不到宿主机的数据库的，所有jar包需要动态加载配置文件
#   以应对可能出现的更改
#    network_mode: "host"
    build: .
    ports: 
      - "8020:8020"
    command: ["/app/wait-for-it.sh","192.168.3.15:3306","--","java","-jar","/app/user.jar"]

