version: "3"
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: 
      - 33060:3306
    volumes:
      - "./db/database:/var/lib/mysql"
      - "./db/init:/docker-entrypoint-initdb.d/"
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    hostname: db

  adminer:
    image: adminer
    restart: always
    ports:
       - 8080:8080
    hostname: adminer

  # 指定应用服务名称
  user:
    # 指定网路模式
    network_mode: "host"
    # 指定要使用的镜像
    build: ./user
    # 指定端口映射, 宿主机端口：容器端口
    ports: 
      - "8020:8020"
    # 设置镜像依赖
    depends_on:
      - "db"
    # MySQL将端口映射到了33060端口，那么通过 宿主机IP:33060是可以访问到数据库的
    # 而应用将自己的网络模式设置为 host, 即和宿主机同一IP了，那么直接用 localhost:33060 即可
    command: ["/app/wait-for-it.sh","localhost:33060","--","java","-jar","/app/user.jar"]
    hostname: user






